language: node_js
sudo: required
env: DISPLAY=':99.0'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
- "6.9.0"
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip && unzip chromedriver.zip
script:
- npm test
- node test/analysis/gc-thrash.js
